# Generated by Django 3.1.2 on 2020-10-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
