# Generated by Django 3.1.2 on 2020-10-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
