# Generated by Django 3.1.2 on 2020-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201031_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=True),
        ),
    ]
